; SpaceMelodyLab TOAST v1.1 — кастомная прошивка
; Плата: Arduino Pro Micro Type-C (ATmega32U4, 5V/16MHz)
;
; Сборка:      pio run -e toast_probe        / pio run -e toast_firmware
; Прошивка:    pio run -e toast_probe -t upload
; Монитор:     pio device monitor

[platformio]
src_dir = src
default_envs = toast_firmware

[env]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
monitor_speed = 115200

; --- скетч-зонд для определения распиновки ---
[env:toast_probe]
build_src_filter = +<toast_probe/>

; --- основная прошивка MIDI-контроллера ---
[env:toast_firmware]
build_src_filter = +<toast_firmware/>
lib_deps =
    arduino-libraries/MIDIUSB@^1.0.5
    adafruit/Adafruit SSD1306@^2.5.10
    adafruit/Adafruit GFX Library@^1.11.10
    nrf24/RF24@^1.4.9
